update:
  only:
    - triggers
  tags:
    - oregon-b-shell
  script:
    - ./update_docker.sh commit

apply:
  tags:
    - iowa-c
  only:
    changes:
      - "k8s/*"
    refs:
      - master
  variables:
    KUBECONFIG: /home/gitlab-runner/.kube/iowa-a.kubeconfig
  script:
    - kubectl apply -f k8s
